version: "3.8"
services:
  nginx-http:
    image: nginx
    container_name: nginx-http
    restart: always
    depends_on:
      - caffeinate
    ports:
      - "80:80"
    volumes:
      - ./nginx/http.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
  caffeinate:
    container_name: caffeinate
    build:
      context: ./caffeinate
    depends_on:
      - mongodb
      - machine-learning
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      SESSION_SECRET: ${SESSION_SECRET}
  machine-learning:
    container_name: machine-learning
    build:
      context: ./machine-learning
    ports:
      - "5000:5000"
  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DB}
    ports:
      - "27017:27017"
