version: "3.8"
services:
  nginx:
    restart: always
    build:
      context: ./nginx
    depends_on:
      - caffeinate
    ports:
      - "80:80"
  caffeinate:
    container_name: caffeinate
    build:
      context: ./caffeinate
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      SESSION_SECRET: ${SESSION_SECRET}
  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DB}
    ports:
      - "27017:27017"
