version: "3.8"
services:
  nginx-https:
    image: nginx
    container_name: nginx-https
    restart: always
    depends_on:
      - caffeinate
    ports:
      - "443:443"
    volumes:
      - ./nginx/https.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
  caffeinate:
    container_name: caffeinate
    build:
      context: ./caffeinate
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      SESSION_SECRET: ${SESSION_SECRET}
      GOOGLE_AUTH_CLIENT_ID: ${GOOGLE_AUTH_CLIENT_ID}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      TRANS_HOST: ${TRANS_HOST}
      TRANS_PORT: ${TRANS_PORT}
      REJECT_UNAUTHORIZED: 'true'
  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DB}
    ports:
      - "27017:27017"
