version: "3.8"
services:
  nginx_https:
    container_name: nginx_https
    restart: always
    depends_on:
      - caffeinate
      - nginx_http
    ports:
      - "443:443"
    volumes:
      - ./nginx/https.conf:/etc/nginx/nginx.conf
  certbot:
    image: certbot/certbot
    container_name: certbot
    depends_on:
      - nginx_http
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email ${DOMAIN_EMAIL} -d caffeinate.page --agree-tos
  nginx_http:
    container_name: nginx_http
    restart: always
    depends_on:
      - caffeinate
    ports:
      - "80:80"
    volumes:
      - ./nginx/http.conf:/etc/nginx/nginx.conf
  caffeinate:
    container_name: caffeinate
    build:
      context: ./caffeinate
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      SESSION_SECRET: ${SESSION_SECRET}
  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DB}
    ports:
      - "27017:27017"
